server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/reim?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: 333
    driver-class-name: com.mysql.cj.jdbc.Driver
