// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PacketMode.proto

package com.cs.heart_release_sock.protocol;

public interface AccessOrBuilder extends
    // @@protoc_insertion_point(interface_extends:mode.Access)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string userName = 1;</code>
   * @return The userName.
   */
  java.lang.String getUserName();
  /**
   * <code>string userName = 1;</code>
   * @return The bytes for userName.
   */
  com.google.protobuf.ByteString
      getUserNameBytes();

  /**
   * <code>string userPhoto = 2;</code>
   * @return The userPhoto.
   */
  java.lang.String getUserPhoto();
  /**
   * <code>string userPhoto = 2;</code>
   * @return The bytes for userPhoto.
   */
  com.google.protobuf.ByteString
      getUserPhotoBytes();

  /**
   * <code>.google.protobuf.Timestamp accessTime = 3;</code>
   * @return Whether the accessTime field is set.
   */
  boolean hasAccessTime();
  /**
   * <code>.google.protobuf.Timestamp accessTime = 3;</code>
   * @return The accessTime.
   */
  com.google.protobuf.Timestamp getAccessTime();
  /**
   * <code>.google.protobuf.Timestamp accessTime = 3;</code>
   */
  com.google.protobuf.TimestampOrBuilder getAccessTimeOrBuilder();
}
