// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PacketMode.proto

package com.cs.heart_release_sock.protocol;

/**
 * <pre>
 *访客、收藏
 * </pre>
 *
 * Protobuf type {@code mode.Access}
 */
public final class Access extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:mode.Access)
    AccessOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Access.newBuilder() to construct.
  private Access(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Access() {
    userName_ = "";
    userPhoto_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Access();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Access(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            userName_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            userPhoto_ = s;
            break;
          }
          case 26: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (accessTime_ != null) {
              subBuilder = accessTime_.toBuilder();
            }
            accessTime_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(accessTime_);
              accessTime_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.cs.heart_release_sock.protocol.PacketMode.internal_static_mode_Access_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.cs.heart_release_sock.protocol.PacketMode.internal_static_mode_Access_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.cs.heart_release_sock.protocol.Access.class, com.cs.heart_release_sock.protocol.Access.Builder.class);
  }

  public static final int USERNAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object userName_;
  /**
   * <code>string userName = 1;</code>
   * @return The userName.
   */
  @java.lang.Override
  public java.lang.String getUserName() {
    java.lang.Object ref = userName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      userName_ = s;
      return s;
    }
  }
  /**
   * <code>string userName = 1;</code>
   * @return The bytes for userName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUserNameBytes() {
    java.lang.Object ref = userName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      userName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int USERPHOTO_FIELD_NUMBER = 2;
  private volatile java.lang.Object userPhoto_;
  /**
   * <code>string userPhoto = 2;</code>
   * @return The userPhoto.
   */
  @java.lang.Override
  public java.lang.String getUserPhoto() {
    java.lang.Object ref = userPhoto_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      userPhoto_ = s;
      return s;
    }
  }
  /**
   * <code>string userPhoto = 2;</code>
   * @return The bytes for userPhoto.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUserPhotoBytes() {
    java.lang.Object ref = userPhoto_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      userPhoto_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ACCESSTIME_FIELD_NUMBER = 3;
  private com.google.protobuf.Timestamp accessTime_;
  /**
   * <code>.google.protobuf.Timestamp accessTime = 3;</code>
   * @return Whether the accessTime field is set.
   */
  @java.lang.Override
  public boolean hasAccessTime() {
    return accessTime_ != null;
  }
  /**
   * <code>.google.protobuf.Timestamp accessTime = 3;</code>
   * @return The accessTime.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getAccessTime() {
    return accessTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : accessTime_;
  }
  /**
   * <code>.google.protobuf.Timestamp accessTime = 3;</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getAccessTimeOrBuilder() {
    return getAccessTime();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getUserNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, userName_);
    }
    if (!getUserPhotoBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, userPhoto_);
    }
    if (accessTime_ != null) {
      output.writeMessage(3, getAccessTime());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getUserNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, userName_);
    }
    if (!getUserPhotoBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, userPhoto_);
    }
    if (accessTime_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getAccessTime());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.cs.heart_release_sock.protocol.Access)) {
      return super.equals(obj);
    }
    com.cs.heart_release_sock.protocol.Access other = (com.cs.heart_release_sock.protocol.Access) obj;

    if (!getUserName()
        .equals(other.getUserName())) return false;
    if (!getUserPhoto()
        .equals(other.getUserPhoto())) return false;
    if (hasAccessTime() != other.hasAccessTime()) return false;
    if (hasAccessTime()) {
      if (!getAccessTime()
          .equals(other.getAccessTime())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + USERNAME_FIELD_NUMBER;
    hash = (53 * hash) + getUserName().hashCode();
    hash = (37 * hash) + USERPHOTO_FIELD_NUMBER;
    hash = (53 * hash) + getUserPhoto().hashCode();
    if (hasAccessTime()) {
      hash = (37 * hash) + ACCESSTIME_FIELD_NUMBER;
      hash = (53 * hash) + getAccessTime().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.cs.heart_release_sock.protocol.Access parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cs.heart_release_sock.protocol.Access parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cs.heart_release_sock.protocol.Access parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cs.heart_release_sock.protocol.Access parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cs.heart_release_sock.protocol.Access parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cs.heart_release_sock.protocol.Access parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cs.heart_release_sock.protocol.Access parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.cs.heart_release_sock.protocol.Access parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.cs.heart_release_sock.protocol.Access parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.cs.heart_release_sock.protocol.Access parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.cs.heart_release_sock.protocol.Access parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.cs.heart_release_sock.protocol.Access parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.cs.heart_release_sock.protocol.Access prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *访客、收藏
   * </pre>
   *
   * Protobuf type {@code mode.Access}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:mode.Access)
      com.cs.heart_release_sock.protocol.AccessOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cs.heart_release_sock.protocol.PacketMode.internal_static_mode_Access_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cs.heart_release_sock.protocol.PacketMode.internal_static_mode_Access_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cs.heart_release_sock.protocol.Access.class, com.cs.heart_release_sock.protocol.Access.Builder.class);
    }

    // Construct using com.cs.heart_release_sock.protocol.Access.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      userName_ = "";

      userPhoto_ = "";

      if (accessTimeBuilder_ == null) {
        accessTime_ = null;
      } else {
        accessTime_ = null;
        accessTimeBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.cs.heart_release_sock.protocol.PacketMode.internal_static_mode_Access_descriptor;
    }

    @java.lang.Override
    public com.cs.heart_release_sock.protocol.Access getDefaultInstanceForType() {
      return com.cs.heart_release_sock.protocol.Access.getDefaultInstance();
    }

    @java.lang.Override
    public com.cs.heart_release_sock.protocol.Access build() {
      com.cs.heart_release_sock.protocol.Access result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.cs.heart_release_sock.protocol.Access buildPartial() {
      com.cs.heart_release_sock.protocol.Access result = new com.cs.heart_release_sock.protocol.Access(this);
      result.userName_ = userName_;
      result.userPhoto_ = userPhoto_;
      if (accessTimeBuilder_ == null) {
        result.accessTime_ = accessTime_;
      } else {
        result.accessTime_ = accessTimeBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.cs.heart_release_sock.protocol.Access) {
        return mergeFrom((com.cs.heart_release_sock.protocol.Access)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.cs.heart_release_sock.protocol.Access other) {
      if (other == com.cs.heart_release_sock.protocol.Access.getDefaultInstance()) return this;
      if (!other.getUserName().isEmpty()) {
        userName_ = other.userName_;
        onChanged();
      }
      if (!other.getUserPhoto().isEmpty()) {
        userPhoto_ = other.userPhoto_;
        onChanged();
      }
      if (other.hasAccessTime()) {
        mergeAccessTime(other.getAccessTime());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.cs.heart_release_sock.protocol.Access parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.cs.heart_release_sock.protocol.Access) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object userName_ = "";
    /**
     * <code>string userName = 1;</code>
     * @return The userName.
     */
    public java.lang.String getUserName() {
      java.lang.Object ref = userName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string userName = 1;</code>
     * @return The bytes for userName.
     */
    public com.google.protobuf.ByteString
        getUserNameBytes() {
      java.lang.Object ref = userName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string userName = 1;</code>
     * @param value The userName to set.
     * @return This builder for chaining.
     */
    public Builder setUserName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      userName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string userName = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearUserName() {
      
      userName_ = getDefaultInstance().getUserName();
      onChanged();
      return this;
    }
    /**
     * <code>string userName = 1;</code>
     * @param value The bytes for userName to set.
     * @return This builder for chaining.
     */
    public Builder setUserNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      userName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object userPhoto_ = "";
    /**
     * <code>string userPhoto = 2;</code>
     * @return The userPhoto.
     */
    public java.lang.String getUserPhoto() {
      java.lang.Object ref = userPhoto_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userPhoto_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string userPhoto = 2;</code>
     * @return The bytes for userPhoto.
     */
    public com.google.protobuf.ByteString
        getUserPhotoBytes() {
      java.lang.Object ref = userPhoto_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userPhoto_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string userPhoto = 2;</code>
     * @param value The userPhoto to set.
     * @return This builder for chaining.
     */
    public Builder setUserPhoto(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      userPhoto_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string userPhoto = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearUserPhoto() {
      
      userPhoto_ = getDefaultInstance().getUserPhoto();
      onChanged();
      return this;
    }
    /**
     * <code>string userPhoto = 2;</code>
     * @param value The bytes for userPhoto to set.
     * @return This builder for chaining.
     */
    public Builder setUserPhotoBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      userPhoto_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp accessTime_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> accessTimeBuilder_;
    /**
     * <code>.google.protobuf.Timestamp accessTime = 3;</code>
     * @return Whether the accessTime field is set.
     */
    public boolean hasAccessTime() {
      return accessTimeBuilder_ != null || accessTime_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp accessTime = 3;</code>
     * @return The accessTime.
     */
    public com.google.protobuf.Timestamp getAccessTime() {
      if (accessTimeBuilder_ == null) {
        return accessTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : accessTime_;
      } else {
        return accessTimeBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp accessTime = 3;</code>
     */
    public Builder setAccessTime(com.google.protobuf.Timestamp value) {
      if (accessTimeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        accessTime_ = value;
        onChanged();
      } else {
        accessTimeBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp accessTime = 3;</code>
     */
    public Builder setAccessTime(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (accessTimeBuilder_ == null) {
        accessTime_ = builderForValue.build();
        onChanged();
      } else {
        accessTimeBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp accessTime = 3;</code>
     */
    public Builder mergeAccessTime(com.google.protobuf.Timestamp value) {
      if (accessTimeBuilder_ == null) {
        if (accessTime_ != null) {
          accessTime_ =
            com.google.protobuf.Timestamp.newBuilder(accessTime_).mergeFrom(value).buildPartial();
        } else {
          accessTime_ = value;
        }
        onChanged();
      } else {
        accessTimeBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp accessTime = 3;</code>
     */
    public Builder clearAccessTime() {
      if (accessTimeBuilder_ == null) {
        accessTime_ = null;
        onChanged();
      } else {
        accessTime_ = null;
        accessTimeBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp accessTime = 3;</code>
     */
    public com.google.protobuf.Timestamp.Builder getAccessTimeBuilder() {
      
      onChanged();
      return getAccessTimeFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp accessTime = 3;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getAccessTimeOrBuilder() {
      if (accessTimeBuilder_ != null) {
        return accessTimeBuilder_.getMessageOrBuilder();
      } else {
        return accessTime_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : accessTime_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp accessTime = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getAccessTimeFieldBuilder() {
      if (accessTimeBuilder_ == null) {
        accessTimeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getAccessTime(),
                getParentForChildren(),
                isClean());
        accessTime_ = null;
      }
      return accessTimeBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:mode.Access)
  }

  // @@protoc_insertion_point(class_scope:mode.Access)
  private static final com.cs.heart_release_sock.protocol.Access DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.cs.heart_release_sock.protocol.Access();
  }

  public static com.cs.heart_release_sock.protocol.Access getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Access>
      PARSER = new com.google.protobuf.AbstractParser<Access>() {
    @java.lang.Override
    public Access parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Access(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Access> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Access> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.cs.heart_release_sock.protocol.Access getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

