// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PacketMode.proto

package com.cs.heart_release_sock.protocol;

/**
 * <pre>
 *咨询请求回复
 * </pre>
 *
 * Protobuf type {@code mode.Consult}
 */
public final class Consult extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:mode.Consult)
    ConsultOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Consult.newBuilder() to construct.
  private Consult(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Consult() {
    userName_ = "";
    record_ = "";
    userPhoto_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Consult();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Consult(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            userName_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            record_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            userPhoto_ = s;
            break;
          }
          case 34: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (consultTime_ != null) {
              subBuilder = consultTime_.toBuilder();
            }
            consultTime_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(consultTime_);
              consultTime_ = subBuilder.buildPartial();
            }

            break;
          }
          case 40: {

            access_ = input.readBool();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.cs.heart_release_sock.protocol.PacketMode.internal_static_mode_Consult_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.cs.heart_release_sock.protocol.PacketMode.internal_static_mode_Consult_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.cs.heart_release_sock.protocol.Consult.class, com.cs.heart_release_sock.protocol.Consult.Builder.class);
  }

  public static final int USERNAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object userName_;
  /**
   * <code>string userName = 1;</code>
   * @return The userName.
   */
  @java.lang.Override
  public java.lang.String getUserName() {
    java.lang.Object ref = userName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      userName_ = s;
      return s;
    }
  }
  /**
   * <code>string userName = 1;</code>
   * @return The bytes for userName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUserNameBytes() {
    java.lang.Object ref = userName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      userName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RECORD_FIELD_NUMBER = 2;
  private volatile java.lang.Object record_;
  /**
   * <code>string record = 2;</code>
   * @return The record.
   */
  @java.lang.Override
  public java.lang.String getRecord() {
    java.lang.Object ref = record_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      record_ = s;
      return s;
    }
  }
  /**
   * <code>string record = 2;</code>
   * @return The bytes for record.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRecordBytes() {
    java.lang.Object ref = record_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      record_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int USERPHOTO_FIELD_NUMBER = 3;
  private volatile java.lang.Object userPhoto_;
  /**
   * <code>string userPhoto = 3;</code>
   * @return The userPhoto.
   */
  @java.lang.Override
  public java.lang.String getUserPhoto() {
    java.lang.Object ref = userPhoto_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      userPhoto_ = s;
      return s;
    }
  }
  /**
   * <code>string userPhoto = 3;</code>
   * @return The bytes for userPhoto.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUserPhotoBytes() {
    java.lang.Object ref = userPhoto_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      userPhoto_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CONSULTTIME_FIELD_NUMBER = 4;
  private com.google.protobuf.Timestamp consultTime_;
  /**
   * <code>.google.protobuf.Timestamp consultTime = 4;</code>
   * @return Whether the consultTime field is set.
   */
  @java.lang.Override
  public boolean hasConsultTime() {
    return consultTime_ != null;
  }
  /**
   * <code>.google.protobuf.Timestamp consultTime = 4;</code>
   * @return The consultTime.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getConsultTime() {
    return consultTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : consultTime_;
  }
  /**
   * <code>.google.protobuf.Timestamp consultTime = 4;</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getConsultTimeOrBuilder() {
    return getConsultTime();
  }

  public static final int ACCESS_FIELD_NUMBER = 5;
  private boolean access_;
  /**
   * <code>bool access = 5;</code>
   * @return The access.
   */
  @java.lang.Override
  public boolean getAccess() {
    return access_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getUserNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, userName_);
    }
    if (!getRecordBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, record_);
    }
    if (!getUserPhotoBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, userPhoto_);
    }
    if (consultTime_ != null) {
      output.writeMessage(4, getConsultTime());
    }
    if (access_ != false) {
      output.writeBool(5, access_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getUserNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, userName_);
    }
    if (!getRecordBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, record_);
    }
    if (!getUserPhotoBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, userPhoto_);
    }
    if (consultTime_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getConsultTime());
    }
    if (access_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(5, access_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.cs.heart_release_sock.protocol.Consult)) {
      return super.equals(obj);
    }
    com.cs.heart_release_sock.protocol.Consult other = (com.cs.heart_release_sock.protocol.Consult) obj;

    if (!getUserName()
        .equals(other.getUserName())) return false;
    if (!getRecord()
        .equals(other.getRecord())) return false;
    if (!getUserPhoto()
        .equals(other.getUserPhoto())) return false;
    if (hasConsultTime() != other.hasConsultTime()) return false;
    if (hasConsultTime()) {
      if (!getConsultTime()
          .equals(other.getConsultTime())) return false;
    }
    if (getAccess()
        != other.getAccess()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + USERNAME_FIELD_NUMBER;
    hash = (53 * hash) + getUserName().hashCode();
    hash = (37 * hash) + RECORD_FIELD_NUMBER;
    hash = (53 * hash) + getRecord().hashCode();
    hash = (37 * hash) + USERPHOTO_FIELD_NUMBER;
    hash = (53 * hash) + getUserPhoto().hashCode();
    if (hasConsultTime()) {
      hash = (37 * hash) + CONSULTTIME_FIELD_NUMBER;
      hash = (53 * hash) + getConsultTime().hashCode();
    }
    hash = (37 * hash) + ACCESS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getAccess());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.cs.heart_release_sock.protocol.Consult parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cs.heart_release_sock.protocol.Consult parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cs.heart_release_sock.protocol.Consult parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cs.heart_release_sock.protocol.Consult parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cs.heart_release_sock.protocol.Consult parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cs.heart_release_sock.protocol.Consult parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cs.heart_release_sock.protocol.Consult parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.cs.heart_release_sock.protocol.Consult parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.cs.heart_release_sock.protocol.Consult parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.cs.heart_release_sock.protocol.Consult parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.cs.heart_release_sock.protocol.Consult parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.cs.heart_release_sock.protocol.Consult parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.cs.heart_release_sock.protocol.Consult prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *咨询请求回复
   * </pre>
   *
   * Protobuf type {@code mode.Consult}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:mode.Consult)
      com.cs.heart_release_sock.protocol.ConsultOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cs.heart_release_sock.protocol.PacketMode.internal_static_mode_Consult_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cs.heart_release_sock.protocol.PacketMode.internal_static_mode_Consult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cs.heart_release_sock.protocol.Consult.class, com.cs.heart_release_sock.protocol.Consult.Builder.class);
    }

    // Construct using com.cs.heart_release_sock.protocol.Consult.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      userName_ = "";

      record_ = "";

      userPhoto_ = "";

      if (consultTimeBuilder_ == null) {
        consultTime_ = null;
      } else {
        consultTime_ = null;
        consultTimeBuilder_ = null;
      }
      access_ = false;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.cs.heart_release_sock.protocol.PacketMode.internal_static_mode_Consult_descriptor;
    }

    @java.lang.Override
    public com.cs.heart_release_sock.protocol.Consult getDefaultInstanceForType() {
      return com.cs.heart_release_sock.protocol.Consult.getDefaultInstance();
    }

    @java.lang.Override
    public com.cs.heart_release_sock.protocol.Consult build() {
      com.cs.heart_release_sock.protocol.Consult result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.cs.heart_release_sock.protocol.Consult buildPartial() {
      com.cs.heart_release_sock.protocol.Consult result = new com.cs.heart_release_sock.protocol.Consult(this);
      result.userName_ = userName_;
      result.record_ = record_;
      result.userPhoto_ = userPhoto_;
      if (consultTimeBuilder_ == null) {
        result.consultTime_ = consultTime_;
      } else {
        result.consultTime_ = consultTimeBuilder_.build();
      }
      result.access_ = access_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.cs.heart_release_sock.protocol.Consult) {
        return mergeFrom((com.cs.heart_release_sock.protocol.Consult)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.cs.heart_release_sock.protocol.Consult other) {
      if (other == com.cs.heart_release_sock.protocol.Consult.getDefaultInstance()) return this;
      if (!other.getUserName().isEmpty()) {
        userName_ = other.userName_;
        onChanged();
      }
      if (!other.getRecord().isEmpty()) {
        record_ = other.record_;
        onChanged();
      }
      if (!other.getUserPhoto().isEmpty()) {
        userPhoto_ = other.userPhoto_;
        onChanged();
      }
      if (other.hasConsultTime()) {
        mergeConsultTime(other.getConsultTime());
      }
      if (other.getAccess() != false) {
        setAccess(other.getAccess());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.cs.heart_release_sock.protocol.Consult parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.cs.heart_release_sock.protocol.Consult) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object userName_ = "";
    /**
     * <code>string userName = 1;</code>
     * @return The userName.
     */
    public java.lang.String getUserName() {
      java.lang.Object ref = userName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string userName = 1;</code>
     * @return The bytes for userName.
     */
    public com.google.protobuf.ByteString
        getUserNameBytes() {
      java.lang.Object ref = userName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string userName = 1;</code>
     * @param value The userName to set.
     * @return This builder for chaining.
     */
    public Builder setUserName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      userName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string userName = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearUserName() {
      
      userName_ = getDefaultInstance().getUserName();
      onChanged();
      return this;
    }
    /**
     * <code>string userName = 1;</code>
     * @param value The bytes for userName to set.
     * @return This builder for chaining.
     */
    public Builder setUserNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      userName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object record_ = "";
    /**
     * <code>string record = 2;</code>
     * @return The record.
     */
    public java.lang.String getRecord() {
      java.lang.Object ref = record_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        record_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string record = 2;</code>
     * @return The bytes for record.
     */
    public com.google.protobuf.ByteString
        getRecordBytes() {
      java.lang.Object ref = record_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        record_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string record = 2;</code>
     * @param value The record to set.
     * @return This builder for chaining.
     */
    public Builder setRecord(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      record_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string record = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearRecord() {
      
      record_ = getDefaultInstance().getRecord();
      onChanged();
      return this;
    }
    /**
     * <code>string record = 2;</code>
     * @param value The bytes for record to set.
     * @return This builder for chaining.
     */
    public Builder setRecordBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      record_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object userPhoto_ = "";
    /**
     * <code>string userPhoto = 3;</code>
     * @return The userPhoto.
     */
    public java.lang.String getUserPhoto() {
      java.lang.Object ref = userPhoto_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userPhoto_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string userPhoto = 3;</code>
     * @return The bytes for userPhoto.
     */
    public com.google.protobuf.ByteString
        getUserPhotoBytes() {
      java.lang.Object ref = userPhoto_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userPhoto_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string userPhoto = 3;</code>
     * @param value The userPhoto to set.
     * @return This builder for chaining.
     */
    public Builder setUserPhoto(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      userPhoto_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string userPhoto = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearUserPhoto() {
      
      userPhoto_ = getDefaultInstance().getUserPhoto();
      onChanged();
      return this;
    }
    /**
     * <code>string userPhoto = 3;</code>
     * @param value The bytes for userPhoto to set.
     * @return This builder for chaining.
     */
    public Builder setUserPhotoBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      userPhoto_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp consultTime_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> consultTimeBuilder_;
    /**
     * <code>.google.protobuf.Timestamp consultTime = 4;</code>
     * @return Whether the consultTime field is set.
     */
    public boolean hasConsultTime() {
      return consultTimeBuilder_ != null || consultTime_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp consultTime = 4;</code>
     * @return The consultTime.
     */
    public com.google.protobuf.Timestamp getConsultTime() {
      if (consultTimeBuilder_ == null) {
        return consultTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : consultTime_;
      } else {
        return consultTimeBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp consultTime = 4;</code>
     */
    public Builder setConsultTime(com.google.protobuf.Timestamp value) {
      if (consultTimeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        consultTime_ = value;
        onChanged();
      } else {
        consultTimeBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp consultTime = 4;</code>
     */
    public Builder setConsultTime(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (consultTimeBuilder_ == null) {
        consultTime_ = builderForValue.build();
        onChanged();
      } else {
        consultTimeBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp consultTime = 4;</code>
     */
    public Builder mergeConsultTime(com.google.protobuf.Timestamp value) {
      if (consultTimeBuilder_ == null) {
        if (consultTime_ != null) {
          consultTime_ =
            com.google.protobuf.Timestamp.newBuilder(consultTime_).mergeFrom(value).buildPartial();
        } else {
          consultTime_ = value;
        }
        onChanged();
      } else {
        consultTimeBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp consultTime = 4;</code>
     */
    public Builder clearConsultTime() {
      if (consultTimeBuilder_ == null) {
        consultTime_ = null;
        onChanged();
      } else {
        consultTime_ = null;
        consultTimeBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp consultTime = 4;</code>
     */
    public com.google.protobuf.Timestamp.Builder getConsultTimeBuilder() {
      
      onChanged();
      return getConsultTimeFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp consultTime = 4;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getConsultTimeOrBuilder() {
      if (consultTimeBuilder_ != null) {
        return consultTimeBuilder_.getMessageOrBuilder();
      } else {
        return consultTime_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : consultTime_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp consultTime = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getConsultTimeFieldBuilder() {
      if (consultTimeBuilder_ == null) {
        consultTimeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getConsultTime(),
                getParentForChildren(),
                isClean());
        consultTime_ = null;
      }
      return consultTimeBuilder_;
    }

    private boolean access_ ;
    /**
     * <code>bool access = 5;</code>
     * @return The access.
     */
    @java.lang.Override
    public boolean getAccess() {
      return access_;
    }
    /**
     * <code>bool access = 5;</code>
     * @param value The access to set.
     * @return This builder for chaining.
     */
    public Builder setAccess(boolean value) {
      
      access_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool access = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearAccess() {
      
      access_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:mode.Consult)
  }

  // @@protoc_insertion_point(class_scope:mode.Consult)
  private static final com.cs.heart_release_sock.protocol.Consult DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.cs.heart_release_sock.protocol.Consult();
  }

  public static com.cs.heart_release_sock.protocol.Consult getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Consult>
      PARSER = new com.google.protobuf.AbstractParser<Consult>() {
    @java.lang.Override
    public Consult parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Consult(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Consult> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Consult> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.cs.heart_release_sock.protocol.Consult getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

