// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PacketMode.proto

package com.cs.heart_release_sock.protocol;

public interface ConsultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:mode.Consult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string userName = 1;</code>
   * @return The userName.
   */
  java.lang.String getUserName();
  /**
   * <code>string userName = 1;</code>
   * @return The bytes for userName.
   */
  com.google.protobuf.ByteString
      getUserNameBytes();

  /**
   * <code>string record = 2;</code>
   * @return The record.
   */
  java.lang.String getRecord();
  /**
   * <code>string record = 2;</code>
   * @return The bytes for record.
   */
  com.google.protobuf.ByteString
      getRecordBytes();

  /**
   * <code>string userPhoto = 3;</code>
   * @return The userPhoto.
   */
  java.lang.String getUserPhoto();
  /**
   * <code>string userPhoto = 3;</code>
   * @return The bytes for userPhoto.
   */
  com.google.protobuf.ByteString
      getUserPhotoBytes();

  /**
   * <code>.google.protobuf.Timestamp consultTime = 4;</code>
   * @return Whether the consultTime field is set.
   */
  boolean hasConsultTime();
  /**
   * <code>.google.protobuf.Timestamp consultTime = 4;</code>
   * @return The consultTime.
   */
  com.google.protobuf.Timestamp getConsultTime();
  /**
   * <code>.google.protobuf.Timestamp consultTime = 4;</code>
   */
  com.google.protobuf.TimestampOrBuilder getConsultTimeOrBuilder();

  /**
   * <code>bool access = 5;</code>
   * @return The access.
   */
  boolean getAccess();
}
