// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PacketMode.proto

package com.cs.heart_release_sock.protocol;

/**
 * <pre>
 *点赞、评论、咨询
 * </pre>
 *
 * Protobuf type {@code mode.Message}
 */
public final class Message extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:mode.Message)
    MessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Message.newBuilder() to construct.
  private Message(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Message() {
    userName_ = "";
    content_ = "";
    userPhoto_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Message();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Message(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            userName_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            content_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            userPhoto_ = s;
            break;
          }
          case 34: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (messageTime_ != null) {
              subBuilder = messageTime_.toBuilder();
            }
            messageTime_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(messageTime_);
              messageTime_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.cs.heart_release_sock.protocol.PacketMode.internal_static_mode_Message_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.cs.heart_release_sock.protocol.PacketMode.internal_static_mode_Message_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.cs.heart_release_sock.protocol.Message.class, com.cs.heart_release_sock.protocol.Message.Builder.class);
  }

  public static final int USERNAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object userName_;
  /**
   * <code>string userName = 1;</code>
   * @return The userName.
   */
  @java.lang.Override
  public java.lang.String getUserName() {
    java.lang.Object ref = userName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      userName_ = s;
      return s;
    }
  }
  /**
   * <code>string userName = 1;</code>
   * @return The bytes for userName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUserNameBytes() {
    java.lang.Object ref = userName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      userName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CONTENT_FIELD_NUMBER = 2;
  private volatile java.lang.Object content_;
  /**
   * <code>string content = 2;</code>
   * @return The content.
   */
  @java.lang.Override
  public java.lang.String getContent() {
    java.lang.Object ref = content_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      content_ = s;
      return s;
    }
  }
  /**
   * <code>string content = 2;</code>
   * @return The bytes for content.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getContentBytes() {
    java.lang.Object ref = content_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      content_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int USERPHOTO_FIELD_NUMBER = 3;
  private volatile java.lang.Object userPhoto_;
  /**
   * <code>string userPhoto = 3;</code>
   * @return The userPhoto.
   */
  @java.lang.Override
  public java.lang.String getUserPhoto() {
    java.lang.Object ref = userPhoto_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      userPhoto_ = s;
      return s;
    }
  }
  /**
   * <code>string userPhoto = 3;</code>
   * @return The bytes for userPhoto.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUserPhotoBytes() {
    java.lang.Object ref = userPhoto_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      userPhoto_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MESSAGETIME_FIELD_NUMBER = 4;
  private com.google.protobuf.Timestamp messageTime_;
  /**
   * <code>.google.protobuf.Timestamp messageTime = 4;</code>
   * @return Whether the messageTime field is set.
   */
  @java.lang.Override
  public boolean hasMessageTime() {
    return messageTime_ != null;
  }
  /**
   * <code>.google.protobuf.Timestamp messageTime = 4;</code>
   * @return The messageTime.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getMessageTime() {
    return messageTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : messageTime_;
  }
  /**
   * <code>.google.protobuf.Timestamp messageTime = 4;</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getMessageTimeOrBuilder() {
    return getMessageTime();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getUserNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, userName_);
    }
    if (!getContentBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, content_);
    }
    if (!getUserPhotoBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, userPhoto_);
    }
    if (messageTime_ != null) {
      output.writeMessage(4, getMessageTime());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getUserNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, userName_);
    }
    if (!getContentBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, content_);
    }
    if (!getUserPhotoBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, userPhoto_);
    }
    if (messageTime_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getMessageTime());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.cs.heart_release_sock.protocol.Message)) {
      return super.equals(obj);
    }
    com.cs.heart_release_sock.protocol.Message other = (com.cs.heart_release_sock.protocol.Message) obj;

    if (!getUserName()
        .equals(other.getUserName())) return false;
    if (!getContent()
        .equals(other.getContent())) return false;
    if (!getUserPhoto()
        .equals(other.getUserPhoto())) return false;
    if (hasMessageTime() != other.hasMessageTime()) return false;
    if (hasMessageTime()) {
      if (!getMessageTime()
          .equals(other.getMessageTime())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + USERNAME_FIELD_NUMBER;
    hash = (53 * hash) + getUserName().hashCode();
    hash = (37 * hash) + CONTENT_FIELD_NUMBER;
    hash = (53 * hash) + getContent().hashCode();
    hash = (37 * hash) + USERPHOTO_FIELD_NUMBER;
    hash = (53 * hash) + getUserPhoto().hashCode();
    if (hasMessageTime()) {
      hash = (37 * hash) + MESSAGETIME_FIELD_NUMBER;
      hash = (53 * hash) + getMessageTime().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.cs.heart_release_sock.protocol.Message parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cs.heart_release_sock.protocol.Message parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cs.heart_release_sock.protocol.Message parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cs.heart_release_sock.protocol.Message parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cs.heart_release_sock.protocol.Message parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cs.heart_release_sock.protocol.Message parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cs.heart_release_sock.protocol.Message parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.cs.heart_release_sock.protocol.Message parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.cs.heart_release_sock.protocol.Message parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.cs.heart_release_sock.protocol.Message parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.cs.heart_release_sock.protocol.Message parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.cs.heart_release_sock.protocol.Message parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.cs.heart_release_sock.protocol.Message prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *点赞、评论、咨询
   * </pre>
   *
   * Protobuf type {@code mode.Message}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:mode.Message)
      com.cs.heart_release_sock.protocol.MessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cs.heart_release_sock.protocol.PacketMode.internal_static_mode_Message_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cs.heart_release_sock.protocol.PacketMode.internal_static_mode_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cs.heart_release_sock.protocol.Message.class, com.cs.heart_release_sock.protocol.Message.Builder.class);
    }

    // Construct using com.cs.heart_release_sock.protocol.Message.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      userName_ = "";

      content_ = "";

      userPhoto_ = "";

      if (messageTimeBuilder_ == null) {
        messageTime_ = null;
      } else {
        messageTime_ = null;
        messageTimeBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.cs.heart_release_sock.protocol.PacketMode.internal_static_mode_Message_descriptor;
    }

    @java.lang.Override
    public com.cs.heart_release_sock.protocol.Message getDefaultInstanceForType() {
      return com.cs.heart_release_sock.protocol.Message.getDefaultInstance();
    }

    @java.lang.Override
    public com.cs.heart_release_sock.protocol.Message build() {
      com.cs.heart_release_sock.protocol.Message result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.cs.heart_release_sock.protocol.Message buildPartial() {
      com.cs.heart_release_sock.protocol.Message result = new com.cs.heart_release_sock.protocol.Message(this);
      result.userName_ = userName_;
      result.content_ = content_;
      result.userPhoto_ = userPhoto_;
      if (messageTimeBuilder_ == null) {
        result.messageTime_ = messageTime_;
      } else {
        result.messageTime_ = messageTimeBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.cs.heart_release_sock.protocol.Message) {
        return mergeFrom((com.cs.heart_release_sock.protocol.Message)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.cs.heart_release_sock.protocol.Message other) {
      if (other == com.cs.heart_release_sock.protocol.Message.getDefaultInstance()) return this;
      if (!other.getUserName().isEmpty()) {
        userName_ = other.userName_;
        onChanged();
      }
      if (!other.getContent().isEmpty()) {
        content_ = other.content_;
        onChanged();
      }
      if (!other.getUserPhoto().isEmpty()) {
        userPhoto_ = other.userPhoto_;
        onChanged();
      }
      if (other.hasMessageTime()) {
        mergeMessageTime(other.getMessageTime());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.cs.heart_release_sock.protocol.Message parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.cs.heart_release_sock.protocol.Message) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object userName_ = "";
    /**
     * <code>string userName = 1;</code>
     * @return The userName.
     */
    public java.lang.String getUserName() {
      java.lang.Object ref = userName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string userName = 1;</code>
     * @return The bytes for userName.
     */
    public com.google.protobuf.ByteString
        getUserNameBytes() {
      java.lang.Object ref = userName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string userName = 1;</code>
     * @param value The userName to set.
     * @return This builder for chaining.
     */
    public Builder setUserName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      userName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string userName = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearUserName() {
      
      userName_ = getDefaultInstance().getUserName();
      onChanged();
      return this;
    }
    /**
     * <code>string userName = 1;</code>
     * @param value The bytes for userName to set.
     * @return This builder for chaining.
     */
    public Builder setUserNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      userName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object content_ = "";
    /**
     * <code>string content = 2;</code>
     * @return The content.
     */
    public java.lang.String getContent() {
      java.lang.Object ref = content_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        content_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string content = 2;</code>
     * @return The bytes for content.
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      java.lang.Object ref = content_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string content = 2;</code>
     * @param value The content to set.
     * @return This builder for chaining.
     */
    public Builder setContent(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      content_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string content = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearContent() {
      
      content_ = getDefaultInstance().getContent();
      onChanged();
      return this;
    }
    /**
     * <code>string content = 2;</code>
     * @param value The bytes for content to set.
     * @return This builder for chaining.
     */
    public Builder setContentBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      content_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object userPhoto_ = "";
    /**
     * <code>string userPhoto = 3;</code>
     * @return The userPhoto.
     */
    public java.lang.String getUserPhoto() {
      java.lang.Object ref = userPhoto_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userPhoto_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string userPhoto = 3;</code>
     * @return The bytes for userPhoto.
     */
    public com.google.protobuf.ByteString
        getUserPhotoBytes() {
      java.lang.Object ref = userPhoto_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userPhoto_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string userPhoto = 3;</code>
     * @param value The userPhoto to set.
     * @return This builder for chaining.
     */
    public Builder setUserPhoto(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      userPhoto_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string userPhoto = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearUserPhoto() {
      
      userPhoto_ = getDefaultInstance().getUserPhoto();
      onChanged();
      return this;
    }
    /**
     * <code>string userPhoto = 3;</code>
     * @param value The bytes for userPhoto to set.
     * @return This builder for chaining.
     */
    public Builder setUserPhotoBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      userPhoto_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp messageTime_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> messageTimeBuilder_;
    /**
     * <code>.google.protobuf.Timestamp messageTime = 4;</code>
     * @return Whether the messageTime field is set.
     */
    public boolean hasMessageTime() {
      return messageTimeBuilder_ != null || messageTime_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp messageTime = 4;</code>
     * @return The messageTime.
     */
    public com.google.protobuf.Timestamp getMessageTime() {
      if (messageTimeBuilder_ == null) {
        return messageTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : messageTime_;
      } else {
        return messageTimeBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp messageTime = 4;</code>
     */
    public Builder setMessageTime(com.google.protobuf.Timestamp value) {
      if (messageTimeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        messageTime_ = value;
        onChanged();
      } else {
        messageTimeBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp messageTime = 4;</code>
     */
    public Builder setMessageTime(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (messageTimeBuilder_ == null) {
        messageTime_ = builderForValue.build();
        onChanged();
      } else {
        messageTimeBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp messageTime = 4;</code>
     */
    public Builder mergeMessageTime(com.google.protobuf.Timestamp value) {
      if (messageTimeBuilder_ == null) {
        if (messageTime_ != null) {
          messageTime_ =
            com.google.protobuf.Timestamp.newBuilder(messageTime_).mergeFrom(value).buildPartial();
        } else {
          messageTime_ = value;
        }
        onChanged();
      } else {
        messageTimeBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp messageTime = 4;</code>
     */
    public Builder clearMessageTime() {
      if (messageTimeBuilder_ == null) {
        messageTime_ = null;
        onChanged();
      } else {
        messageTime_ = null;
        messageTimeBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp messageTime = 4;</code>
     */
    public com.google.protobuf.Timestamp.Builder getMessageTimeBuilder() {
      
      onChanged();
      return getMessageTimeFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp messageTime = 4;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getMessageTimeOrBuilder() {
      if (messageTimeBuilder_ != null) {
        return messageTimeBuilder_.getMessageOrBuilder();
      } else {
        return messageTime_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : messageTime_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp messageTime = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getMessageTimeFieldBuilder() {
      if (messageTimeBuilder_ == null) {
        messageTimeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getMessageTime(),
                getParentForChildren(),
                isClean());
        messageTime_ = null;
      }
      return messageTimeBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:mode.Message)
  }

  // @@protoc_insertion_point(class_scope:mode.Message)
  private static final com.cs.heart_release_sock.protocol.Message DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.cs.heart_release_sock.protocol.Message();
  }

  public static com.cs.heart_release_sock.protocol.Message getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Message>
      PARSER = new com.google.protobuf.AbstractParser<Message>() {
    @java.lang.Override
    public Message parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Message(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Message> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Message> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.cs.heart_release_sock.protocol.Message getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

