// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PacketMode.proto

package com.cs.heart_release_sock.protocol;

public final class PacketMode {
  private PacketMode() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mode_Packet_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mode_Packet_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mode_Position_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mode_Position_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mode_Photo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mode_Photo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mode_Call_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mode_Call_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mode_Message_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mode_Message_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mode_Consult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mode_Consult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mode_Access_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mode_Access_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020PacketMode.proto\022\004mode\032\037google/protobu" +
      "f/timestamp.proto\">\n\006Packet\022\014\n\004code\030\001 \001(" +
      "\005\022\014\n\004body\030\002 \001(\014\022\014\n\004from\030\003 \001(\005\022\n\n\002to\030\004 \001(" +
      "\005\"/\n\010Position\022\020\n\010latitude\030\001 \001(\001\022\021\n\tlongi" +
      "tude\030\002 \001(\001\"E\n\005Photo\022\r\n\005photo\030\001 \001(\014\022-\n\tph" +
      "otoTime\030\002 \001(\0132\032.google.protobuf.Timestam" +
      "p\"(\n\004Call\022\016\n\006userId\030\001 \001(\t\022\020\n\010userName\030\002 " +
      "\001(\t\"p\n\007Message\022\020\n\010userName\030\001 \001(\t\022\017\n\007cont" +
      "ent\030\002 \001(\t\022\021\n\tuserPhoto\030\003 \001(\t\022/\n\013messageT" +
      "ime\030\004 \001(\0132\032.google.protobuf.Timestamp\"\177\n" +
      "\007Consult\022\020\n\010userName\030\001 \001(\t\022\016\n\006record\030\002 \001" +
      "(\t\022\021\n\tuserPhoto\030\003 \001(\t\022/\n\013consultTime\030\004 \001" +
      "(\0132\032.google.protobuf.Timestamp\022\016\n\006access" +
      "\030\005 \001(\010\"]\n\006Access\022\020\n\010userName\030\001 \001(\t\022\021\n\tus" +
      "erPhoto\030\002 \001(\t\022.\n\naccessTime\030\003 \001(\0132\032.goog" +
      "le.protobuf.Timestamp*\244\002\n\010Protocol\022\024\n\020Pr" +
      "otocol_Default\020\000\022\016\n\tHeartbeat\020\350\007\022\023\n\016User" +
      "_No_Online\020\320\017\022\022\n\rUser_Position\020\270\027\022\022\n\rUse" +
      "r_Thumb_Up\020\240\037\022\021\n\014User_Comment\020\210\'\022\024\n\017User" +
      "_Consulting\020\360.\022\027\n\022User_Communication\020\3306\022" +
      "\035\n\030User_Communication_photo\020\300>\022\016\n\tUser_C" +
      "all\020\250F\022\020\n\013User_Access\020\220N\022\024\n\017User_Collect" +
      "ion\020\370U\022\034\n\027User_Consulting_Consult\020\340]B)\n\"" +
      "com.cs.heart_release_sock.protocolP\001\210\001\001b" +
      "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_mode_Packet_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_mode_Packet_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mode_Packet_descriptor,
        new java.lang.String[] { "Code", "Body", "From", "To", });
    internal_static_mode_Position_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_mode_Position_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mode_Position_descriptor,
        new java.lang.String[] { "Latitude", "Longitude", });
    internal_static_mode_Photo_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_mode_Photo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mode_Photo_descriptor,
        new java.lang.String[] { "Photo", "PhotoTime", });
    internal_static_mode_Call_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_mode_Call_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mode_Call_descriptor,
        new java.lang.String[] { "UserId", "UserName", });
    internal_static_mode_Message_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_mode_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mode_Message_descriptor,
        new java.lang.String[] { "UserName", "Content", "UserPhoto", "MessageTime", });
    internal_static_mode_Consult_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_mode_Consult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mode_Consult_descriptor,
        new java.lang.String[] { "UserName", "Record", "UserPhoto", "ConsultTime", "Access", });
    internal_static_mode_Access_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_mode_Access_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mode_Access_descriptor,
        new java.lang.String[] { "UserName", "UserPhoto", "AccessTime", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
