// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PacketMode.proto

package com.cs.heart_release_sock.protocol;

public interface PacketOrBuilder extends
    // @@protoc_insertion_point(interface_extends:mode.Packet)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 code = 1;</code>
   * @return The code.
   */
  int getCode();

  /**
   * <code>bytes body = 2;</code>
   * @return The body.
   */
  com.google.protobuf.ByteString getBody();

  /**
   * <code>int32 from = 3;</code>
   * @return The from.
   */
  int getFrom();

  /**
   * <code>int32 to = 4;</code>
   * @return The to.
   */
  int getTo();
}
