// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PacketMode.proto

package com.cs.heart_release_sock.protocol;

public interface PhotoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:mode.Photo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes photo = 1;</code>
   * @return The photo.
   */
  com.google.protobuf.ByteString getPhoto();

  /**
   * <code>.google.protobuf.Timestamp photoTime = 2;</code>
   * @return Whether the photoTime field is set.
   */
  boolean hasPhotoTime();
  /**
   * <code>.google.protobuf.Timestamp photoTime = 2;</code>
   * @return The photoTime.
   */
  com.google.protobuf.Timestamp getPhotoTime();
  /**
   * <code>.google.protobuf.Timestamp photoTime = 2;</code>
   */
  com.google.protobuf.TimestampOrBuilder getPhotoTimeOrBuilder();
}
