// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PacketMode.proto

package com.cs.heart_release_sock.protocol;

/**
 * <pre>
 *发送图片
 * </pre>
 *
 * Protobuf type {@code mode.Photo}
 */
public final class Photo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:mode.Photo)
    PhotoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Photo.newBuilder() to construct.
  private Photo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Photo() {
    photo_ = com.google.protobuf.ByteString.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Photo();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Photo(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {

            photo_ = input.readBytes();
            break;
          }
          case 18: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (photoTime_ != null) {
              subBuilder = photoTime_.toBuilder();
            }
            photoTime_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(photoTime_);
              photoTime_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.cs.heart_release_sock.protocol.PacketMode.internal_static_mode_Photo_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.cs.heart_release_sock.protocol.PacketMode.internal_static_mode_Photo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.cs.heart_release_sock.protocol.Photo.class, com.cs.heart_release_sock.protocol.Photo.Builder.class);
  }

  public static final int PHOTO_FIELD_NUMBER = 1;
  private com.google.protobuf.ByteString photo_;
  /**
   * <code>bytes photo = 1;</code>
   * @return The photo.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getPhoto() {
    return photo_;
  }

  public static final int PHOTOTIME_FIELD_NUMBER = 2;
  private com.google.protobuf.Timestamp photoTime_;
  /**
   * <code>.google.protobuf.Timestamp photoTime = 2;</code>
   * @return Whether the photoTime field is set.
   */
  @java.lang.Override
  public boolean hasPhotoTime() {
    return photoTime_ != null;
  }
  /**
   * <code>.google.protobuf.Timestamp photoTime = 2;</code>
   * @return The photoTime.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getPhotoTime() {
    return photoTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : photoTime_;
  }
  /**
   * <code>.google.protobuf.Timestamp photoTime = 2;</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getPhotoTimeOrBuilder() {
    return getPhotoTime();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!photo_.isEmpty()) {
      output.writeBytes(1, photo_);
    }
    if (photoTime_ != null) {
      output.writeMessage(2, getPhotoTime());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!photo_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(1, photo_);
    }
    if (photoTime_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getPhotoTime());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.cs.heart_release_sock.protocol.Photo)) {
      return super.equals(obj);
    }
    com.cs.heart_release_sock.protocol.Photo other = (com.cs.heart_release_sock.protocol.Photo) obj;

    if (!getPhoto()
        .equals(other.getPhoto())) return false;
    if (hasPhotoTime() != other.hasPhotoTime()) return false;
    if (hasPhotoTime()) {
      if (!getPhotoTime()
          .equals(other.getPhotoTime())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PHOTO_FIELD_NUMBER;
    hash = (53 * hash) + getPhoto().hashCode();
    if (hasPhotoTime()) {
      hash = (37 * hash) + PHOTOTIME_FIELD_NUMBER;
      hash = (53 * hash) + getPhotoTime().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.cs.heart_release_sock.protocol.Photo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cs.heart_release_sock.protocol.Photo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cs.heart_release_sock.protocol.Photo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cs.heart_release_sock.protocol.Photo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cs.heart_release_sock.protocol.Photo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cs.heart_release_sock.protocol.Photo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cs.heart_release_sock.protocol.Photo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.cs.heart_release_sock.protocol.Photo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.cs.heart_release_sock.protocol.Photo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.cs.heart_release_sock.protocol.Photo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.cs.heart_release_sock.protocol.Photo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.cs.heart_release_sock.protocol.Photo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.cs.heart_release_sock.protocol.Photo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *发送图片
   * </pre>
   *
   * Protobuf type {@code mode.Photo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:mode.Photo)
      com.cs.heart_release_sock.protocol.PhotoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cs.heart_release_sock.protocol.PacketMode.internal_static_mode_Photo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cs.heart_release_sock.protocol.PacketMode.internal_static_mode_Photo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cs.heart_release_sock.protocol.Photo.class, com.cs.heart_release_sock.protocol.Photo.Builder.class);
    }

    // Construct using com.cs.heart_release_sock.protocol.Photo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      photo_ = com.google.protobuf.ByteString.EMPTY;

      if (photoTimeBuilder_ == null) {
        photoTime_ = null;
      } else {
        photoTime_ = null;
        photoTimeBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.cs.heart_release_sock.protocol.PacketMode.internal_static_mode_Photo_descriptor;
    }

    @java.lang.Override
    public com.cs.heart_release_sock.protocol.Photo getDefaultInstanceForType() {
      return com.cs.heart_release_sock.protocol.Photo.getDefaultInstance();
    }

    @java.lang.Override
    public com.cs.heart_release_sock.protocol.Photo build() {
      com.cs.heart_release_sock.protocol.Photo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.cs.heart_release_sock.protocol.Photo buildPartial() {
      com.cs.heart_release_sock.protocol.Photo result = new com.cs.heart_release_sock.protocol.Photo(this);
      result.photo_ = photo_;
      if (photoTimeBuilder_ == null) {
        result.photoTime_ = photoTime_;
      } else {
        result.photoTime_ = photoTimeBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.cs.heart_release_sock.protocol.Photo) {
        return mergeFrom((com.cs.heart_release_sock.protocol.Photo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.cs.heart_release_sock.protocol.Photo other) {
      if (other == com.cs.heart_release_sock.protocol.Photo.getDefaultInstance()) return this;
      if (other.getPhoto() != com.google.protobuf.ByteString.EMPTY) {
        setPhoto(other.getPhoto());
      }
      if (other.hasPhotoTime()) {
        mergePhotoTime(other.getPhotoTime());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.cs.heart_release_sock.protocol.Photo parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.cs.heart_release_sock.protocol.Photo) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.google.protobuf.ByteString photo_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes photo = 1;</code>
     * @return The photo.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getPhoto() {
      return photo_;
    }
    /**
     * <code>bytes photo = 1;</code>
     * @param value The photo to set.
     * @return This builder for chaining.
     */
    public Builder setPhoto(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      photo_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes photo = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearPhoto() {
      
      photo_ = getDefaultInstance().getPhoto();
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp photoTime_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> photoTimeBuilder_;
    /**
     * <code>.google.protobuf.Timestamp photoTime = 2;</code>
     * @return Whether the photoTime field is set.
     */
    public boolean hasPhotoTime() {
      return photoTimeBuilder_ != null || photoTime_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp photoTime = 2;</code>
     * @return The photoTime.
     */
    public com.google.protobuf.Timestamp getPhotoTime() {
      if (photoTimeBuilder_ == null) {
        return photoTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : photoTime_;
      } else {
        return photoTimeBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp photoTime = 2;</code>
     */
    public Builder setPhotoTime(com.google.protobuf.Timestamp value) {
      if (photoTimeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        photoTime_ = value;
        onChanged();
      } else {
        photoTimeBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp photoTime = 2;</code>
     */
    public Builder setPhotoTime(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (photoTimeBuilder_ == null) {
        photoTime_ = builderForValue.build();
        onChanged();
      } else {
        photoTimeBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp photoTime = 2;</code>
     */
    public Builder mergePhotoTime(com.google.protobuf.Timestamp value) {
      if (photoTimeBuilder_ == null) {
        if (photoTime_ != null) {
          photoTime_ =
            com.google.protobuf.Timestamp.newBuilder(photoTime_).mergeFrom(value).buildPartial();
        } else {
          photoTime_ = value;
        }
        onChanged();
      } else {
        photoTimeBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp photoTime = 2;</code>
     */
    public Builder clearPhotoTime() {
      if (photoTimeBuilder_ == null) {
        photoTime_ = null;
        onChanged();
      } else {
        photoTime_ = null;
        photoTimeBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp photoTime = 2;</code>
     */
    public com.google.protobuf.Timestamp.Builder getPhotoTimeBuilder() {
      
      onChanged();
      return getPhotoTimeFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp photoTime = 2;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getPhotoTimeOrBuilder() {
      if (photoTimeBuilder_ != null) {
        return photoTimeBuilder_.getMessageOrBuilder();
      } else {
        return photoTime_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : photoTime_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp photoTime = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getPhotoTimeFieldBuilder() {
      if (photoTimeBuilder_ == null) {
        photoTimeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getPhotoTime(),
                getParentForChildren(),
                isClean());
        photoTime_ = null;
      }
      return photoTimeBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:mode.Photo)
  }

  // @@protoc_insertion_point(class_scope:mode.Photo)
  private static final com.cs.heart_release_sock.protocol.Photo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.cs.heart_release_sock.protocol.Photo();
  }

  public static com.cs.heart_release_sock.protocol.Photo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Photo>
      PARSER = new com.google.protobuf.AbstractParser<Photo>() {
    @java.lang.Override
    public Photo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Photo(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Photo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Photo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.cs.heart_release_sock.protocol.Photo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

