// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PacketMode.proto

package com.cs.heart_release_sock.protocol;

public interface PositionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:mode.Position)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double latitude = 1;</code>
   * @return The latitude.
   */
  double getLatitude();

  /**
   * <code>double longitude = 2;</code>
   * @return The longitude.
   */
  double getLongitude();
}
